kakaotech-25/moheng

- .github/workflows/code-review.yml
#18 
gpt-turbo-3.5 모델을 사용하여 풀리퀘스트를 감지하고 자동으로 리뷰를 남기도록 구현하였습니다.
단계별 프롬프팅을 통해 리뷰 결과를 구체적이고 효과적으로 받아볼 수 있도록 추가했습니다.
> #18 feat: gpt action 리뷰봇 설정하는 yml

- backend/Dockerfile
#2 
- JDK 버전 수정(gradle 버전 8.8)
- gradle 설정파일 복사
- gradle 파일 실행 권한 부여
- gradle 파일 의존성 다운로드
- 호스트 운영체제의 현재 디렉토리의 src 파일을 복사하여 이미지 상의 /app/src에 복사
- 컨테이너 내부에서 최소권한 설정
- 컨테이너 실행 시 ./gradlew bootRun 명령어 실행
> [feat]Backend Dockerfile 설정

- backend/.dockerignore
- backend/Dockerfile
- compose.yaml
#2
- 컴포즈 파일추가
- gradlew 권한 에러 수정
> [Feature] composefile 작성

- backend/build.gradle
- backend/src/main/java/moheng/auth/application/AuthService.java
- backend/src/main/java/moheng/auth/application/AuthService.kt
- backend/src/main/java/moheng/auth/domain/JwtTokenProvider.java
- backend/src/main/java/moheng/auth/domain/KakaoOAuthClient.java
- backend/src/main/java/moheng/auth/domain/KakaoUriProvider.java
- backend/src/main/java/moheng/auth/domain/OAuthAccessToken.java
- backend/src/main/java/moheng/auth/domain/OAuthClient.java
- backend/src/main/java/moheng/auth/domain/OAuthMember.java
- backend/src/main/java/moheng/auth/domain/OAuthUriProvider.java
- backend/src/main/java/moheng/auth/dto/AuthRequest.java
- backend/src/main/java/moheng/auth/dto/AuthResponse.java
- backend/src/main/java/moheng/auth/dto/OAuthUriResponse.java
- backend/src/main/java/moheng/auth/dto/TokenRequest.java
- backend/src/main/java/moheng/auth/dto/TokenResponse.java
- backend/src/main/java/moheng/auth/exception/AuthException.java
- backend/src/main/java/moheng/auth/exception/InvalidTokenException.java
- backend/src/main/java/moheng/auth/presentation/AuthController.java
- backend/src/main/java/moheng/global/config/RestTemplateConfig.java
- backend/src/main/java/moheng/global/config/WebConfig.java
- backend/src/main/java/moheng/member/application/MemberService.java
- backend/src/main/java/moheng/member/domain/Member.java
- backend/src/main/java/moheng/member/domain/repository/MemberRepository.java
- backend/src/main/java/moheng/member/exception/NoExistMemberException.java
- backend/src/main/resources/application.yml
- backend/src/test/java/moheng/auth/application/AuthServiceTest.java
- backend/src/test/java/moheng/auth/presentation/AuthControllerTest.java
- backend/src/test/java/moheng/config/StubOAuthClient.java
- backend/src/test/java/moheng/config/TestConfig.java
- backend/src/test/resources/application.yml
#12 
- Authorization Code 를 URI 의 Query String 으로 담아서 전송해주는 API 를 구현했습니다.
- Authorization Code 로 Token 을 생성하는 API 를 구현했습니다
- RestTemplate, WebMvcConfig 등 소셜 로그인을 위한 의존성 설정 정보를 Infrastructure Layer 에 추가했습니다.
- 관련 단위 테스트를 작성했습니다.
> [feat] 소셜 로그인을 위한 Token 및 Authorization Code 발급 기능 구현

- backend/src/main/java/moheng/auth/domain/JwtTokenProvider.java
- backend/src/main/java/moheng/auth/domain/OAuthMember.java
- backend/src/main/java/moheng/auth/dto/AuthRequest.java
- backend/src/main/java/moheng/auth/dto/AuthResponse.java
- backend/src/main/java/moheng/member/application/MemberService.java
- backend/src/test/java/moheng/auth/application/AuthServiceTest.java
- backend/src/test/java/moheng/auth/domain/JwtTokenProviderTest.java
- backend/src/test/java/moheng/config/StubOAuthClient.java
- backend/src/test/java/moheng/member/application/MemberServiceTest.java
- backend/src/test/java/moheng/member/domain/MemberRepositoryTest.java
#26  
- JwtTokenProvider 테스트 코드 추가
- MemberService 테스트 코드 추가
-  MemberRepository 테스트 코드 추가
> [test] 회원 및 소셜 로그인 관련 코드에 대한 테스트 코드 추가

- backend/src/main/java/moheng/auth/application/AuthService.java
- backend/src/main/java/moheng/auth/domain/OAuthMember.java
- backend/src/main/java/moheng/member/application/MemberService.java
- backend/src/main/java/moheng/member/domain/GenderType.java
- backend/src/main/java/moheng/member/domain/Member.java
- backend/src/main/java/moheng/member/domain/repository/MemberRepository.java
- backend/src/main/java/moheng/member/exception/InvalidBirthdayException.java
- backend/src/main/java/moheng/member/exception/InvalidGenderFormatException.java
- backend/src/test/java/moheng/member/application/MemberServiceTest.java
- backend/src/test/java/moheng/member/domain/MemberRepositoryTest.java
- backend/src/test/java/moheng/member/domain/MemberTest.java
#28 
- 누락된 컬럼 추가 : 생년월일, 성별
- 각 컬럼 유효성 검증 및 단위 테스트 진행
- Member 생성자 추가
- OAuthMember 클래스 수정
> [test] 누락된 Member 엔티티 필드 추가 및 단위 테스트 진행

- Jenkinsfile
#2
Jenkinsfile 초기 예시 세팅
EC2 젠킨스와 PR 트리거과 웹훅 연동 테스트
> [feat] 젠킨스파일 초기 예시 세팅

- backend/src/main/java/moheng/auth/application/AuthService.java
- backend/src/main/java/moheng/auth/domain/InMemoryRefreshTokenRepository.java
- backend/src/main/java/moheng/auth/domain/JwtTokenProvider.java
- backend/src/main/java/moheng/auth/domain/RefreshTokenRepository.java
- backend/src/main/java/moheng/auth/dto/Accessor.java
- backend/src/main/java/moheng/auth/dto/LogoutRequest.java
- backend/src/main/java/moheng/auth/dto/RenewalAccessTokenRequest.java
- backend/src/main/java/moheng/auth/dto/RenewalAccessTokenResponse.java
- backend/src/main/java/moheng/auth/exception/BadRequestException.java
- backend/src/main/java/moheng/auth/exception/NoExistMemberTokenException.java
- backend/src/main/java/moheng/auth/presentation/AuthController.java
- backend/src/main/java/moheng/auth/presentation/admin/AdminAuthenticationArgumentResolver.java
- backend/src/main/java/moheng/auth/presentation/authentication/AuthenticationArgumentResolver.java
- backend/src/main/java/moheng/member/presentation/MemberController.java
- backend/src/test/java/moheng/auth/application/AuthServiceTest.java
- backend/src/test/java/moheng/auth/domain/JwtTokenProviderTest.java
- backend/src/test/java/moheng/config/DatabaseCleaner.java
- backend/src/test/java/moheng/config/RepositoryTestConfig.java
- backend/src/test/java/moheng/config/ServiceTestConfig.java
- backend/src/test/java/moheng/member/application/MemberServiceTest.java
- backend/src/test/java/moheng/member/domain/MemberRepositoryTest.java
#35 
#39  
- #39 과 중복되어 PR 이 올라갔는데, 이 점 참고바랍니다. 다음부턴 천천히 PR 올려야겠어요 ㅋㅋㅋㅋ
> [feat] RefreshToken 으로 새로운 AccessToken 을 재발급하는 기능, 로그아웃 기능 구현

- backend/src/main/java/moheng/auth/dto/AccessTokenResponse.java
- backend/src/main/java/moheng/auth/presentation/AuthController.java
- backend/src/main/java/moheng/auth/presentation/authentication/Authentication.java
- backend/src/main/java/moheng/auth/presentation/authentication/AuthenticationArgumentResolver.java
- backend/src/main/java/moheng/auth/presentation/authentication/AuthenticationBearerExtractor.java
- backend/src/main/java/moheng/auth/presentation/authentication/AuthenticationWebConfig.java
- backend/src/main/java/moheng/member/presentation/MemberController.java
- backend/src/test/java/moheng/auth/domain/JwtTokenManagerTest.java
- backend/src/test/java/moheng/auth/presentation/AuthControllerTest.java
- backend/src/test/java/moheng/config/ControllerTestConfig.java
- backend/src/test/java/moheng/fixture/AuthFixtures.java
- backend/src/test/java/moheng/fixture/MemberFixtures.java
- backend/src/test/java/moheng/member/presentation/MemberControllerTest.java
#55 
인증/인가 도메인의 프레젠테이션 계층에 대한 단위 테스트를 진행했습니다.
> [test] 인증/인가 도메인 프레젠테이션 계층 단위 테스트 진행

- backend/src/main/java/moheng/auth/dto/AccessTokenResponse.java
- backend/src/main/java/moheng/auth/presentation/AuthController.java
- backend/src/main/java/moheng/auth/presentation/admin/AdminAuthenticationArgumentResolver.java
- backend/src/main/java/moheng/auth/presentation/admin/AdminAuthenticationWebConfig.java
- backend/src/main/java/moheng/auth/presentation/authentication/Authentication.java
- backend/src/main/java/moheng/auth/presentation/authentication/AuthenticationArgumentResolver.java
- backend/src/main/java/moheng/auth/presentation/authentication/AuthenticationBearerExtractor.java
- backend/src/main/java/moheng/auth/presentation/authentication/AuthenticationWebConfig.java
- backend/src/main/java/moheng/member/dto/response/MemberResponse.java
- backend/src/main/java/moheng/member/presentation/MemberController.java
- backend/src/test/java/moheng/auth/domain/JwtTokenManagerTest.java
- backend/src/test/java/moheng/auth/presentation/AuthControllerTest.java
- backend/src/test/java/moheng/config/ControllerTestConfig.java
- backend/src/test/java/moheng/fixture/AuthFixtures.java
- backend/src/test/java/moheng/fixture/MemberFixtures.java
- backend/src/test/java/moheng/member/presentation/MemberControllerTest.java
#58 
- ArgumentResolver 가 테스트 환경에서 인식되지 않는 현상을 해결했습니다.
- 테스트 환경에서 ControllerTestConfig 내의 ArgumentResolver 관련 객체들을 Autowired 로 실제 객체를 주입받도록 변경했습니다.
> [fix] ArgumentResolver 가 테스트 환경에서 인식되지 않는 현상 해결 

- Jenkinsfile
#20 
- 프론트엔드 빌드 스크립트를 동작하도록 수정했습니다.
- 백엔드 빌드 스크립트를 동작하도록 수정했습니다.
- Jenkins 환경에 JDK 22/ gradle 8.8 / node 22 설치했습니다.
- 백엔드 코드 빌드과정이 약 3분이 넘게 걸리는데 문제되는 부분이 없는지 파이프라인 상에서 더 나은방식으로 구현할 수 있는지 알고싶습니다.
> [feat] jenkins의 CI 과정의 빌드스크립트 구현

- backend/build.gradle
- backend/src/main/java/moheng/auth/presentation/AuthController.java
- backend/src/main/java/moheng/member/dto/response/MemberResponse.java
- backend/src/test/java/moheng/acceptance/AcceptanceTestConfig.java
- backend/src/test/java/moheng/acceptance/AuthAcceptanceTest.java
- backend/src/test/java/moheng/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/moheng/acceptance/config/AcceptanceTestConfig.java
- backend/src/test/java/moheng/acceptance/fixture/AuthAcceptanceFixture.java
- backend/src/test/java/moheng/acceptance/fixture/HttpStatus.java
- backend/src/test/java/moheng/acceptance/fixture/MemberAcceptanceFixture.java
- backend/src/test/java/moheng/config/StubKakaoOAuthClientProvider.java
- backend/src/test/java/moheng/member/application/MemberServiceTest.java
- backend/src/test/java/moheng/member/domain/MemberRepositoryTest.java
#56 
<details>
</details>
- 인증/인가 도메인과 관련한 모든 코드에 대한 E2E 인수 테스트(Acceptance Test) 를 진행했습니다.
> [test] 인증/인가 도메인 전구간 E2E 인수 테스트(Acceptance Test) 진행 

- Taskfile.yml
#22 
<details>
</details>
- 복잡하고 긴 명령어들을 taskfile에서 선언적으로 수행할 수 있습니다. 
- 원하는 구문을 지정한후 `task`와 함께 입력하여 실행합니다.
- go언어 의존성관련 최초설치가 필요합니다. `brew install task`
> [feat] 태스크 파일과 도커관련 명렁어 추가

- compose.frontend.yaml
- frontend/.gitignore
- frontend/Dockerfile.dev
- frontend/install_package.sh
#78 
<details>
</details>
- 프론트 개발환경에서 필요한 node_modules를 컨테이너 재시작에 따라 매번 설치하지 않도록 변경했습니다.
- .gitignore에 pnpm 관련 추적 제거
- 컨테이너 마운트시에 해당 디렉토리 파일이 제거되므로 불필요한 COPY구문 제거를 통해 이미지 사이즈 최적화
> [fix] 프론트 컨테이너의 마운트 지점을 usr/app 으로 변경

- backend/src/main/java/moheng/auth/domain/oauth/KakaoOAuthClient.java
- backend/src/main/java/moheng/auth/domain/oauth/KakaoOAuthMember.java
- backend/src/main/resources/application.yml
- backend/src/test/java/moheng/config/KakaoStubOAuthClient.java
- backend/src/test/resources/application.yml
#27 
<details>
</details>
- Kakao Developers 에 저희 서비스 앱을 등록했습니다. 
- Client ID, Client Secret KEY 를 발급받고 `application.yml` 에 등록해놓은 상태입니다. 하지만, 이와 같이 민감한 정보에 대해서 `Git Submodule` 로 private 으로 감춰야한다고 생각하는데, 이에 대한 의견 부탁드립니다 🙂
> [docs] Kakao Developers 와 모행 서비스 연동 

- backend/src/main/java/moheng/auth/domain/oauth/KakaoOAuthClient.java
- backend/src/main/java/moheng/auth/domain/oauth/KakaoOAuthMember.java
- backend/src/main/java/moheng/auth/domain/oauth/KakaoUriProvider.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/logback-spring.xml
- backend/src/test/java/moheng/config/KakaoStubOAuthClient.java
- backend/src/test/resources/application.yml
#49 
<details>
</details>
- Slf4j 기반 기본적인 logging 전략을 구현했습니다. Logging Level 은 `ERROR`, `WARN`, `INFO` 3가지로 설정했습니다.
> [feat] 기본적인 Slf4j 로깅 전략 구현

- .github/workflows/sonarqube-java.yml
- backend/build.gradle
#99 
<details>
</details>
- build.gradle 플러그인에 소나큐브 최신버전 5.xx 추가
@msung99 java build시에 xml파일이 추출되도록 변경 구현 되어야 소나큐브 동작할것으로 예상됩니다.
> [feat] 소나큐브 백엔드 애플리케이션 분석 코드 추가

- ai/Dockerfile
> #101
<details>
</details>
- ai Dockerfile을 요구조건에 따라 수정했습니다.
> [feat] ai Dockerfile 수정

- Jenkinsfile
#61 
<details>
</details>
- 빌드 결과를 성공/실패에 따라 디스코드 알림으로 받아볼 수 있도록 수정했습니다.
- 빌드 제목, 시간 등 포맷을 지정했니다.
> [feat] 젠킨스 결과 디스코드 알림

- Jenkinsfile
#127 
<details>
</details>
- 젠킨스 CI의 실패시 어떤 부분에서 실패했는지 여부 보여주도록 디스코드 알림 메세지 포맷을 조정했습니다.
- 젠킨스 CI의 실패시 어떤 오류메세지가 출력되었는지 보이도록 로그 메세지를 추출했습니다.
> [feat] 젠킨스의 디스코드 알람 포맷 수정

- backend/src/main/java/moheng/auth/application/AuthService.java
- backend/src/main/java/moheng/recommendtrip/domain/RecommendTripRepository.java
- backend/src/main/java/moheng/trip/application/TripService.java
- backend/src/main/java/moheng/trip/domain/recommendstrategy/AppendRecommendTripStrategy.java
- backend/src/main/java/moheng/trip/domain/recommendstrategy/RecommendTripStrategy.java
- backend/src/main/java/moheng/trip/domain/recommendstrategy/ReplaceRecommendTripStrategy.java
- backend/src/main/java/moheng/trip/domain/recommendstrategy/SaveRecommendTripStrategyProvider.java
- backend/src/main/java/moheng/trip/exception/NoExistRecommendTripStrategyException.java
- backend/src/test/java/moheng/trip/application/AppendRecommendTripStrategyTest.java
- backend/src/test/java/moheng/trip/application/ReplaceRecommendTripStrategyTest.java
#133 
<details>
</details>
- 디자인패턴을 적용하여 선호 여행지 클릭수에 따른 여행지 저장 알고리즘을 캡슐화 했습니다.
+) 빌드 속도 최적화는 이번 PR 이 머지된 후 바로 진행할 예정입니다.
> [refactor] 전략패턴을 적용하여 선호 여행지 클릭수에 따른 여행지 저장 알고리즘 캡슐화 

- backend/src/main/java/moheng/global/error/ControllerAdvice.java
- backend/src/main/java/moheng/keyword/application/KeywordService.java
- backend/src/main/java/moheng/keyword/domain/KeywordRepository.java
- backend/src/main/java/moheng/keyword/domain/TripKeywordRepository.java
- backend/src/main/java/moheng/keyword/presentation/KeywordController.java
- backend/src/main/java/moheng/trip/application/TripService.java
- backend/src/main/java/moheng/trip/dto/FindTripsResponse.java
- backend/src/test/java/moheng/acceptance/KeywordAcceptenceTest.java
- backend/src/test/java/moheng/acceptance/fixture/KeywordAcceptenceFixture.java
- backend/src/test/java/moheng/acceptance/fixture/TripKeywordAcceptenceFixture.java
- backend/src/test/java/moheng/keyword/application/KeywordServiceTest.java
- backend/src/test/java/moheng/keyword/domain/KeywordRepositoryTest.java
- backend/src/test/java/moheng/keyword/domain/TripKeywordRepositoryTest.java
- backend/src/test/java/moheng/keyword/presentation/KeywordControllerTest.java
- backend/src/test/java/moheng/trip/application/TripServiceTest.java
#109 
<details>
</details>
- 비회원에게 랜덤 키워드, 여행지 클릭횟수에 기반하여 추천 여행지를 제공하는 기능을 구현했습니다.
> [feat] 비회원에게 랜덤 키워드, 여행지 클릭횟수에 기반하여 추천 여행지를 제공하는 기능 구현 

- Taskfile.yml
- backend/Dockerfile
- compose.dev.yaml
- frontend/package.json
- frontend/src/api/Axios.js
- frontend/src/api/AxiosTestComponent.jsx
#151 
<details>
</details>
- npm install 하는 경우 나는 eslint 모듈 충돌 문제 해결
- docker compose file 추가
- task dev 명령어 추가 (백엔드 서버와 프론트 서버 둘다 가동)
> [feat] 서버 연동 도커컴포즈 파일 추가

- compose.dev.yaml
- nginx/Dockerfile
- nginx/tools/default.conf
#152 
<details>
</details>
- nginx 컨테이너 설정 추가
- default.conf 파일 추가
- upstream블록
- api/ prefix를 사용한 리소스 구분 
- 애플리케이션 확장시 로드밸런싱을 위한 주석 추가
- nginx를 사용한 로그 수집전략에 대해서 찾아보고 싶어요. 현재는 로그를 따로 저장하고 있지 않습니다.
> [feat] nginx 컨테이너 설정 

- Jenkinsfile
> #172 
<details>
</details>
- Jenkinsfile에서 Frontend Build와 Backend Build를 parallel을 통해 병렬로 빌드하게 수정하였습니다.
> [feat] Jenkinsfile 프론트엔드, 백엔드 병렬 빌드 구현

- .github/workflows/sonarqube-java.yml
- .github/workflows/sonarqube-javascript.yml
- backend/build.gradle
> #187 
<details>
</details>
- 기존 demo 프로젝트(백엔드 프로젝트)를 moheng-backend로 변경하였습니다.
> [feat] sonarcloud backend 프로젝트 변경 및 수정

- backend/build.gradle
> #191 
<details>
</details>
- 백엔드 소나큐브 프로젝트 이름을 명시하여 자동으로 이름이 변경되지 않도록 수정했습니다.
> [fix] 백엔드 소나클라우드 프로젝트 이름 설정 추가

- Taskfile.yml
- compose.prod.yaml
- nginx/.gitignore
- nginx/nginx.conf
- nginx/ssl/init_tls.sh
- nginx/tools/production.conf
> #198 
<details>
</details>
- openssl 인증서 생성 스크립트, nginx설정파일추가
- ipv4 v6 소켓 reused 옵션 설정
- 로깅전략: 로그 포맷 / 에러 정책 추가
- 컨테이너 재시작 옵션 unless-stopped로변경 (의도적 시그널 외 에러시 재시작)
- nginx 컨테이너 443포트포워딩
> [feat] 배포용 nginx 컨테이너 설정

- Jenkinsfile
#200 
<details>
</details>
-  agent 를 any로 설정하여 바로 수행하도록 변경했습니다.
> [fix] 젠킨스 이중 샌드박스 문제 해결

- Taskfile.yml
- deploy.sh
> #208 
<details>
</details>
- 배포 스크립트 추가
- 추후 서브모듈로 분리
> [feat] 개발서버 배포를 위한 스크립트 작성

- backend/src/main/java/moheng/planner/application/PlannerService.java
- backend/src/main/java/moheng/planner/application/TripScheduleService.java
- backend/src/main/java/moheng/planner/dto/AddTripOnScheduleRequests.java
- backend/src/main/java/moheng/planner/presentation/TripScheduleController.java
- backend/src/test/java/moheng/acceptance/TripScheduleAcceptenceTest.java
- backend/src/test/java/moheng/acceptance/fixture/TripScheduleAcceptenceTestFixture.java
- backend/src/test/java/moheng/planner/application/PlannerServiceTest.java
- backend/src/test/java/moheng/planner/application/TripScheduleServiceTest.java
- backend/src/test/java/moheng/planner/presentation/TripScheduleControllerTest.java
> #220 
<details>
</details>
- 현재 여행지을 픓래너의 여러 일정에 담을 수 있도록 변경했습니다.
> [feat] 현재 여행지를 플래너의 여러 일정에 담을 수 있도록 변경

- backend/src/main/java/moheng/keyword/application/KeywordService.java
- backend/src/main/java/moheng/keyword/dto/FindAllKeywordResponse.java
- backend/src/main/java/moheng/keyword/dto/FindAllKeywordResponses.java
- backend/src/main/java/moheng/keyword/presentation/KeywordController.java
- backend/src/main/java/moheng/planner/application/PlannerService.java
- backend/src/main/java/moheng/planner/application/TripScheduleService.java
- backend/src/main/java/moheng/planner/dto/AddTripOnScheduleRequests.java
- backend/src/main/java/moheng/planner/presentation/TripScheduleController.java
- backend/src/test/java/moheng/acceptance/KeywordAcceptenceTest.java
- backend/src/test/java/moheng/acceptance/TripScheduleAcceptenceTest.java
- backend/src/test/java/moheng/acceptance/fixture/KeywordAcceptenceFixture.java
- backend/src/test/java/moheng/acceptance/fixture/TripScheduleAcceptenceTestFixture.java
- backend/src/test/java/moheng/keyword/application/KeywordServiceTest.java
- backend/src/test/java/moheng/keyword/presentation/KeywordControllerTest.java
- backend/src/test/java/moheng/planner/application/PlannerServiceTest.java
- backend/src/test/java/moheng/planner/application/TripScheduleServiceTest.java
- backend/src/test/java/moheng/planner/presentation/TripScheduleControllerTest.java
> #233 
<details>
</details>
- 메인페이지에서 보여줄 키워드 리스트 조회 API 를 구현했습니다.
> [feat] 키워드 리스트 조회 API 구현 

- backend/build.gradle
- backend/src/main/java/moheng/keyword/application/KeywordService.java
- backend/src/main/java/moheng/keyword/dto/FindAllKeywordResponse.java
- backend/src/main/java/moheng/keyword/dto/FindAllKeywordResponses.java
- backend/src/main/java/moheng/keyword/presentation/KeywordController.java
- backend/src/main/java/moheng/planner/application/PlannerService.java
- backend/src/main/java/moheng/planner/application/TripScheduleService.java
- backend/src/main/java/moheng/planner/dto/AddTripOnScheduleRequests.java
- backend/src/main/java/moheng/planner/presentation/TripScheduleController.java
- backend/src/main/resources/application.yml
- backend/src/test/java/moheng/acceptance/KeywordAcceptenceTest.java
- backend/src/test/java/moheng/acceptance/TripScheduleAcceptenceTest.java
- backend/src/test/java/moheng/acceptance/fixture/KeywordAcceptenceFixture.java
- backend/src/test/java/moheng/acceptance/fixture/TripScheduleAcceptenceTestFixture.java
- backend/src/test/java/moheng/keyword/application/KeywordServiceTest.java
- backend/src/test/java/moheng/keyword/presentation/KeywordControllerTest.java
- backend/src/test/java/moheng/planner/application/PlannerServiceTest.java
- backend/src/test/java/moheng/planner/application/TripScheduleServiceTest.java
- backend/src/test/java/moheng/planner/presentation/TripScheduleControllerTest.java
> [docs] 소셜 로그인 Redirect URI 설정

- backend/src/main/resources/application.yml
> #115 (논외)
<details>
</details>
> [fix] ddl-auto 를 update 로 지정

- frontend/package-lock.json
- frontend/src/App.jsx
- frontend/src/pages/Login/Callback.jsx
- frontend/src/pages/Login/Login.jsx
- frontend/src/pages/Login/axiosInstance.jsx
> #143
<details>
</details>
- 카카오 소셜 로그인 연동 작업을 수행했습니다.
- baseURL로 http://localhost:8080/api 를 설정하여 사용했습니다.
- 우선 로그인 완료 후 메인화면으로 넘어오도록 되어있습니다.
> [feat] 카카오 소셜 로그인 구현

- backend/src/docs/asciidoc/signup.adoc
- backend/src/main/java/moheng/auth/application/AuthService.java
- backend/src/main/java/moheng/auth/domain/oauth/OAuthMember.java
- backend/src/main/java/moheng/auth/infrastructure/KakaoOAuthMember.java
- backend/src/main/java/moheng/member/application/MemberService.java
- backend/src/main/java/moheng/member/domain/Member.java
- backend/src/main/java/moheng/member/dto/request/SignUpProfileRequest.java
- backend/src/main/resources/static/docs/index.html
- backend/src/test/java/moheng/acceptance/fixture/MemberAcceptanceFixture.java
- backend/src/test/java/moheng/config/stub/KakaoStubOAuthClient.java
- backend/src/test/java/moheng/fixture/MemberFixtures.java
- backend/src/test/java/moheng/member/application/MemberServiceTest.java
- backend/src/test/java/moheng/member/domain/MemberRepositoryTest.java
- backend/src/test/java/moheng/member/domain/MemberTest.java
- backend/src/test/java/moheng/member/presentation/MemberControllerTest.java
> #248 
<details>
</details>
- 소셜 로그인 유저의 프로필 이미지를 받아와서 저장하도록 변경
> [feat] 소셜 로그인 유저의 프로필 이미지를 받아와서 저장하도록 변경 

- nginx/tools/production.conf
#217 
<details>
</details>
- 서버에 존재하는 configuration과 코드 내용을 맞추었습니다.
> [fix] nginx 인증서 발급 완료 버전 

- frontend/.gitignore
- frontend/src/pages/PlannerDetails/PlannerDetails.jsx
> #260
<details>
</details>
- 키값을 깃에 바로 올리면 유출될 가능성이 있어 환경변수로 설정하였습니다.
> [refactor] 카카오 디벨로퍼스 키값 환경변수로 설정하기

- ai/model/Recommendation.py
- ai/model_serving/application/model_service.py
- ai/model_serving/domain/repository/model_repo.py
- ai/model_serving/infra/repository/model_repo.py
- ai/model_serving/interface/controllers/model_controller.py
> #259
<details>
- [*] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. [feat] 소셜 로그인 구현
- [*] 💯 빌드와 테스트는 잘 통과했나요?
- [*] 🧹 불필요한 코드는 제거했나요?
- [*] 💭 이슈는 등록했나요?
- [*] 🏷️ 라벨은 등록했나요?
- [*] 🙇‍♂️ 리뷰어를 지정했나요? (페어가 존재할 시)
</details>
- `/travel/custom/model`의 request body를 변경했습니다.
변경 후
```json
{
"preferredLocation": [
{
"contentId": 1918639,
"clicked": 1
}
]
}
```
- `/travel/custom/model` 및 `/travel/similar/{contentId}`의 작동 오류를 수정했습니다.
- @msung99 DTO 파일은 어떤 단위로 분리하면 좋을까요?
- 테스트로 확인한 부분 추가
> [Hotfix] 서빙 모듈 핫픽스

- frontend/src/components/UserForm/UserForm.jsx
- frontend/src/pages/Login/Callback.jsx
- frontend/src/pages/Profile/Profile.jsx
> #229
<details>
</details>
- 최초입력1-기본정보 페이지의 연동 작업을 수행했습니다.
- 닉네임 중복검사를 진행하여 중복 닉네임을 처리합니다.
- 닉네임이 50글자를 넘으면 입력이 안되도록 해두었습니다.
- 생년월일이 현재보다 이후의 날짜라면 입력이 안되도록 해두었습니다.
- 닉네임, 생년월일, 성별을 모두 입력해야 다음 페이지로 넘어가도록 했고, 다 입력이 되었다면 서버로 넘겨주어 저장되도록 구현했습니다.
> [feat] 최초입력1- 기본정보 페이지 프론트 백 연동 작업

- .gitmodules
> #263
<details>
</details>
- init.sql 파일의 rank 예약어를 백틱으로 감싸서 충돌을 막았습니다. 추후 다른이름으로 변경이 필요해보입니다.
> [feat] 데이터베이스 서브모듈 연결

- ai/Dockerfile
> #267 
<details>
</details>
- docker의 런타임과 poetry 실행시점에 직접 포트를 포워딩하여 api요청이 막히는 현상을 해결했습니다.
- poetry의 가상화 옵션을 제거해서 별도의 가상화 오버헤드를 개선하였습니다. (도커 자체가 격리된 프로세스이기 때문에 별도의 의존성 관리가 필요하지 않습니다.)
> [Hotfix] ai 컨테이너 요청 거부 문제 해결

- backend/src/main/java/moheng/global/mdc/AsyncConfig.java
- backend/src/main/java/moheng/global/mdc/MdcFilter.java
- backend/src/main/java/moheng/global/mdc/MdcTaskDecorator.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/static/docs/index.html
> #280 
<details>
</details>
h2 인메모리로 임시 전환
> [hotfix] MySQL 데이터베이스를 h2 인메모리로 임시 전환 

- compose.frontend.yaml
- frontend/src/pages/LivingInfo/LivingInfo.jsx
- frontend/src/pages/Login/axiosInstance.jsx
- frontend/src/pages/Profile/Profile.jsx
> #230
<details>
</details>
- 최초입력2-생활정보입력 페이지에서 선택된 버튼의 정보를 백으로 넘겨주도록 구현하였습니다.
> [feat] 최초입력2-생활정보입력 페이지 프론트 백 연동 작업

- backend/src/main/java/moheng/applicationrunner/dev/TripDevApplicationRunner.java
- backend/src/main/java/moheng/global/mdcfilter/AsyncConfig.java
- backend/src/main/java/moheng/global/mdcfilter/MdcFilter.java
- backend/src/main/java/moheng/global/mdcfilter/MdcTaskDecorator.java
- backend/src/main/java/moheng/liveinformation/domain/TripLiveInformation.java
- backend/src/main/resources/logback-spring.xml
> #216 
<details>
</details>
- 더미데이터 삽입 연산의 성능 개선 : JdbcTemplate 벌크 연산 활용
> [refactor] 대량 데이터 삽입 쿼리 성능 최적화를 위한 JdbcTemplate Batch Insert 작성

- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/moheng.iml
- .idea/poetry.xml
- .idea/vcs.xml
- ai/README.md
- ai/main.py
- ai/model_serving/application/model_service.py
- ai/model_serving/application/model_service_test.py
- ai/model_serving/domain/repository/model_repo.py
- ai/model_serving/infra/repository/model_repo.py
- ai/model_serving/interface/controllers/model_controller.py
- ai/model_serving/interface/model/location.py
> #265 
<details>
</details>
- 에러로 제거한 모델 모듈 의존성을 서빙 코드에 다시 연결했습니다.
- 다음 PR에서 테스트 코드를 추가하겠습니다...
> [feat] 모델 서빙 코드에 더미 모델 모듈 연결

- backend/src/main/java/moheng/member/application/MemberService.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/static/docs/index.html
> #290 
<details>
</details>
회원가입시 누락되는 프로필 이미지 삽입
> [fix] 회원가입시 누락되는 프로필 이미지 삽입

- backend/.dockerignore
- backend/Dockerfile.dev
- backend/Dockerfile.prod
- compose.dev.yaml
> #299 
<details>
</details>
- task dev를 실행해도 백엔드의 디렉토리를 마운트 하지 않도록 수정했습니다.
- dockerfile.prod 멀티스테이징 파일의 복사를 더 직관적인 경로에 두어 실행을 하도록 수정했습니다.
> [hotfix] task dev를 실행했을때 snapshot.jar를 찾지 못하는 문제 해결

- backend/src/main/java/moheng/keyword/domain/repository/TripKeywordRepository.java
- backend/src/main/java/moheng/member/presentation/MemberController.java
- backend/src/main/java/moheng/trip/domain/repository/TripRepository.java
- backend/src/main/resources/application.yml
> #298 
<details>
</details>
- 플래너, 추천 여행, 여행 도메인에 발생하는 N+1 문제를 해결했습니다.
- 외부 AI 연동 API 호출 로직에서 발생하는 N+1 문제 해결은, 향후 AI 연동 완료시 구현할 예정입니다.
> [refactor] 플래너, 추천 여행, 여행 도메인에 발생하는 N+1 문제 해결 

- backend/src/main/java/moheng/member/domain/Member.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/static/docs/index.html
- backend/src/test/java/moheng/fixture/LiveInformationFixture.java
> #275 
<details>
</details>
- springboot graceful shutdown 을 적용하여, 현재 `SIGKILL` 을 시그널로 위험하여 프로세스가 강제 종료되는 문제를 개선했습니다.
- 이젠 `SIGKILL` 이 아닌, `SIGTERM` 시그널을 전송하여 안전하게 프로세스를 종료시키게 됩니다.
-  데드락이 발생하는 상황을 위해, 안전한 프로세스 종료를 위해 대기하는 최대 시간을 20초로 지정했습니다.
> [refactor] 완전한 무중단 배포 환경을 위한 SpringBoot Graceful Shutdown 을 적용 

- backend/src/main/java/moheng/global/config/CorsConfig.java
> #275  (논외)
<details>
</details>
-  CORS 도메인 주소 개방
> chore: CORS 도메인 주소 개방

- ai/main.py
> #309 
<details>
</details>
- 백엔드 앱의 CORS를 허용해 두었습니다.
> [feat] 백엔드 앱의 CORS 설정

- backend/src/main/java/moheng/applicationrunner/dev/MemberLiveInformationDevApplicationRunner.java
- backend/src/main/java/moheng/planner/application/PlannerService.java
- backend/src/main/java/moheng/recommendtrip/domain/tripfilterstrategy/TripPreferredLocationsFilterStrategy.java
- backend/src/main/java/moheng/recommendtrip/dto/PreferredLocationRequest.java
- backend/src/main/java/moheng/trip/dto/RecommendTripsByVisitedLogsRequest.java
- backend/src/main/java/moheng/trip/infrastructure/ExternalAiRecommendModelClient.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/static/docs/index.html
> #311 
<details>
</details>
- 이하 생략
> [Bug] 플래너 일정 수정시 endDate 날짜가 startDate 로 수정되는 현상 

- backend/src/main/resources/application.yml
> [fix] h2 경로 임의 변경

- frontend/src/components/PlannerModal/PlannerModal.jsx
- frontend/src/pages/Login/axiosInstance.jsx
- frontend/src/pages/Planner/Planner.jsx
> #237
<details>
</details>
- 플래너페이지 연동작업을 진행했습니다.
- 일정추가모달을 통해 일정리스트에 일정이 추가되도록 하였습니다.
- 드롭다운메뉴의 수정하기를 통해 일정정보 수정이 가능합니다.
- 드롭다운메뉴의 삭제하기를 통해 일정 삭제가 가능합니다.
> [feat] 플래너페이지 연동작업

- backend/src/main/java/moheng/global/config/CorsConfig.java
> #327 
<details>
</details>
- 쿠키 전송을 위한 추가 CORS 변경
> [docs] 쿠키 전송을 위한 추가 CORS 설정 

- backend/src/main/java/moheng/global/mdcfilter/AsyncConfig.java
- backend/src/main/java/moheng/liveinformation/domain/repository/LiveInformationRepository.java
- backend/src/main/java/moheng/recommendtrip/domain/tripfilterstrategy/TripLiveInformationFilterStrategy.java
- backend/src/main/java/moheng/trip/dto/FindTripResponse.java
- backend/src/test/java/moheng/keyword/presentation/KeywordControllerTest.java
- backend/src/test/java/moheng/recommendtrip/presentation/RecommendTripControllerTest.java
- backend/src/test/java/moheng/trip/application/TripServiceTest.java
- backend/src/test/java/moheng/trip/presentation/TripControllerTest.java
> #307 
<details>
</details>
- FastAPI 서버와의 API 연동을 완료했습니다.
> [feat] FastAPI 서버와의 API 연동 

- backend/src/main/java/moheng/applicationrunner/dev/MemberLiveInformationDevApplicationRunner.java
- backend/src/main/java/moheng/global/error/ControllerAdvice.java
- backend/src/main/java/moheng/member/application/MemberService.java
- backend/src/main/java/moheng/recommendtrip/domain/repository/RecommendTripRepository.java
- backend/src/main/java/moheng/trip/domain/repository/MemberTripRepository.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/static/docs/index.html
- backend/src/test/java/moheng/auth/presentation/AuthControllerTest.java
> #336 
<details>
</details>
- 최초 회원가입시 MemberTrip 저장되지 않는 현상을 해결했습니다.
> [Bug] MemberTrip 저장되지 않는 현상 

- frontend/src/pages/Home/Home.jsx
- frontend/src/pages/Login/Login.css
> #232
<details>
</details>
- 메인페이지에서 키워드 여행지 연동 작업 진행했습니다.
> [feat] 메인페이지 키워드 여행지 연동

- .gitignore
- .idea/moheng.iml
- .idea/vcs.xml
- backend/src/main/resources/static/docs/index.html
- compose.dev.yaml
- frontend/src/components/TravelCarousel/TravelCarousel.jsx
- frontend/src/pages/Home/Home.jsx
- frontend/src/pages/Login/axiosInstance.jsx
- frontend/src/pages/TravelDetails/TravelDetails.jsx
> #232 
<details>
</details>
- 메인 페이지의 AI 추천 API 연동
- 키워드로 필터링하는 UI 추가
- 키워드 필터링 API 연동
> [feat] 메인페이지 연동

- frontend/src/pages/Login/axiosInstance.jsx
> #347
<details>
</details>
- localhost로 api콜을 보내고 있는 문제를 발견하여 baseURL을 수정하였습니다.
> [hotfix] baseURL 수정

- backend/src/main/resources/application.yml
- backend/src/test/java/moheng/member/application/MemberServiceTest.java
> #87
<details>
</details>
- redirect uri 변경된 내용 맞는지만 한 번 봐주세요!
> [docs] redirect uri 임시 변경

- backend/src/main/java/moheng/global/config/CorsConfig.java
> #349 
<details>
</details>
- CORS 추가 설정
> [docs] CORS 추가 설정

- backend/Dockerfile.dev
- backend/run_server.sh
- backend/src/main/java/moheng/trip/infrastructure/ExternalAiRecommendModelClient.java
- backend/src/main/java/moheng/trip/infrastructure/ExternalAiSimilarTripModelClient.java
- compose.dev.yaml
> #354 
<details>
</details>
- 백엔드 컨테이너에서 AI컨테이너로 요청 보내는 부분의 도메인이름을 컨테이너 서비스명으로 수정했습니다.
> [hotfix] 백엔드 -> ai 컨테이너 요청 도메인이름 수정

- compose.dev.yaml
- compose.prod.yaml
- nginx/tools/develop.conf
- nginx/tools/production.conf
> #359 
<details>
</details>
- nginx/src/ 경로를 파일 서빙 디렉토리로 사용하기 위해서 컨테이너 /etc/nginx/src 경로와 마운트 하였습니다.
- nginx의 develop파일과 prod 파일을 업데이트 했습니다.
> [feat] nginx 비디오 서빙 엔드포인트 구축

- frontend/src/pages/Landing/Landing.jsx
- frontend/src/pages/Login/axiosInstance.jsx
- nginx/tools/develop.conf
- nginx/tools/production.conf
> #361 
<details>
</details>
- 프론트엔드 랜딩페이지에 데모영상을 삽입했습니다. 
```shell
https://moheng.life/api/video/moheng.mp4
```
> [feat] 랜딩페이지 데모영상 삽입

- frontend/src/pages/Home/Home.jsx
> #87
<details>
</details>
- 기존 소셜 로그인 API 를 AccessToken도 함께 발급되도록 리팩토링 했습니다. 
- AccessToken의 인증을 어느 레이어에서 구현하는것이 좋을까요?
- 테스트로 확인한 부분 추가
> fix: 로그인 안되면 로그인으로 튕구기

- backend/src/docs/asciidoc/tripschedule.adoc
> #371 
<details>
</details>
- 스닛팻 경로 수정
> [fix] 세부 일정내 여행지 삭제 API 스닛팻 경로 수정

- frontend/src/pages/PlannerDetails/PlannerDetails.jsx
- frontend/src/pages/TravelDetails/TravelDetails.jsx
> #235
<details>
</details>
- 플래너에 담기모달에서 일정추가 버튼을 통해 일정리스트에 새로운 일정이 추가되도록 하였습니다.
- 일정리스트에서 일정 선택 후 저장을 누르면 해당 여행지가 일정에 담기도록 하였습니다.
> [feat] 플래너에 담기 모달을 통해 일정생성 및 여행지 담는 기능

- nginx/Dockerfile.local
- nginx/Dockerfile.prod
> [hotfix] nginx 컨테이너 권한 루트로 수정

- backend/build.gradle
- backend/src/docs/asciidoc/member.adoc
- backend/src/docs/asciidoc/signup.adoc
- backend/src/main/resources/application-prod.yml
> #383 
<details>
</details>
- 빌드 성공 기준을 커버리지 85% 이상으로 설정
> [feat] 빌드 성공 기준을 커버리지 85% 이상으로 설정 및 누락된 API 명세 추가 

- .github/scripts/build/send_discord_pipeline.sh
- .github/workflows/docker-build.yml
> #385 
<details>
</details>
깃헙액션 파이프라인 추가
> [feat] 깃헙 액션 파이프라인 구성

- .github/workflows/docker-build.yml
> #385 
<details>
<summary> PR 체크리스트</summary
- 공식문서에 제시된 방식으로 액션 수정
- https://docs.docker.com/build/ci/github-actions/
> [fix] 도커 레지스트리에 푸시 안되는 문제 해결

- .github/workflows/docker-build.yml
> [test] amd64 만 빌드하도록 수정

- backend/src/main/java/moheng/trip/domain/repository/MemberTripRepository.java
- backend/src/main/resources/application-local.yml
> #301 
<details>
</details>
- 외부 AI 연동 API 호출 로직에서 발생하는 N+1 문제 해결
> [refactor] 외부 AI 연동 API 호출 로직에서 발생하는 N+1 문제 해결 

- backend/src/test/java/moheng/acceptance/RecommendTripAcceptenceTest.java
- backend/src/test/java/moheng/acceptance/fixture/RecommendTripAcceptenceFixture.java
- backend/src/test/java/moheng/recommendtrip/application/RecommendTripServiceTest.java
> #338 
<details>
</details>
- 최초 회원가입 유저가 관심 여행지 입력 후 AI 맞춤 추천 여행지까지의 API 요청에 대한 테스트 코드 추가
> [test] 최초 회원가입 유저가 관심 여행지 입력 후 AI 맞춤 추천 여행지까지의 API 요청에 대한 테스트 코드 추가 

- backend/src/main/java/moheng/planner/application/TripScheduleService.java
> #400 
<details>
</details>
- 세부 일정에서 여행지가 정상적으로 제거되지 않는 문제 해결
> fix: 세부 일정에서 여행지가 정상적으로 제거되지 않는 문제 해결

- backend/src/test/java/moheng/planner/application/TripScheduleServiceTest.java
> #402 
<details>
</details>
- 세부 일정에서 여행지를 제거하는 테스트 코드 추가
> [test] 세부 일정에서 여행지를 제거하는 테스트 코드 추가 

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
> #201 
<details>
</details>
- https://haon.blog/database/hikaricp-theory/ 에 기제한대로 DBCP 사이즈를 최적화 했습니다.
> [feat] HikariCP 데이터베이스 Conntecion Pool 사이즈를 결정 및 적용 

- backend/src/main/java/moheng/applicationrunner/warmup/AuthWarmUpRunner.java
- backend/src/main/java/moheng/applicationrunner/warmup/KeywordWarmUpRunner.java
- backend/src/main/java/moheng/applicationrunner/warmup/MemberWarmUpRunner.java
- backend/src/main/java/moheng/applicationrunner/warmup/PlannerWarmUpRunner.java
- backend/src/main/java/moheng/applicationrunner/warmup/RecommendWarmUpRunner.java
- backend/src/main/java/moheng/applicationrunner/warmup/TripWarmUpRunner.java
> #286 
<details>
</details>
- Warm Up Runner 로깅 추가
> feat: Warm Up Runner 로깅 추가

- frontend/src/pages/PlannerDetails/PlannerDetails.jsx
> #399
<details>
</details>
- 플래너 세부페이지 내에서 연동이 되지 않은 부분을 구현했습니다.
- 여행지를 삭제하면 DB에서 삭제되도록 하였습니다.
- 햄버거 버튼을 사용하여 순서를 변경하면 해당 순서가 유지되도록 하였습니다.
> [feat] 플래너세부페이지 내부 기능 구현

- backend/build.gradle
- backend/src/main/java/moheng/auth/domain/oauth/OAuthClientProvider.java
- backend/src/main/java/moheng/auth/infrastructure/KakaoOAuthClient.java
- backend/src/main/java/moheng/global/error/ControllerAdvice.java
- backend/src/main/java/moheng/liveinformation/domain/MemberLiveInformation.java
- backend/src/main/java/moheng/recommendtrip/presentation/RecommendTripController.java
- backend/src/main/java/moheng/trip/application/TripService.java
- backend/src/main/java/moheng/trip/domain/Trip.java
- backend/src/main/java/moheng/trip/exception/NotAbleToAccessTripByPessimisticLock.java
- backend/src/main/java/moheng/trip/exception/NotAbleToAccessTripByPessimisticLockException.java
- backend/src/test/java/moheng/auth/domain/OAuthClientProviderTest.java
- backend/src/test/java/moheng/keyword/application/KeywordServiceTest.java
- backend/src/test/java/moheng/trip/application/TripServiceTest.java
> #412 
<details>
</details>
- 빌드 성공 기준을 테스트 커버리지 85% 이상일때로 설정하여, 견고하지 못한 애플리케이션을 빌드 자체가 실패하도록 설정했습니다.
- 기타 추가적인 테스트 코드를 추가했습니다.
> [feat] 빌드 성공 기준을 테스트 커버리지 85% 이상일때로 설정

- backend/src/main/java/moheng/trip/infrastructure/ExternalAiRecommendModelClient.java
- backend/src/main/java/moheng/trip/infrastructure/ExternalAiSimilarTripModelClient.java
> #427 
<details>
</details>
- AI 외부 API 호출시 발생하는 예외 처리
> [feat] AI 외부 API 호출시 발생하는 예외 처리 

- compose.prod.yaml
> #421 
<details>
</details>
- 프론트 컨테이너의 환경변수를 세팅했습니다.
> [feat] 프론트 컨테이너 환경변수 파일 세팅

- backend/src/main/java/moheng/global/aopquery/QueryCounterAop.java
- backend/src/main/java/moheng/global/mdcfilter/MdcFilter.java
- backend/src/main/java/moheng/keyword/domain/repository/TripKeywordRepository.java
- backend/src/main/resources/logback-spring.xml
> #433 
<details>
</details>
- MDC 출력 포맷을 더 정확하게 출력하도록 변경
> [refactor] MDC 로 올바르게 쿼리 카운터를 로깅하도록 개선 

- backend/src/main/java/moheng/global/replication/DataSourceConfig.java
- backend/src/main/java/moheng/global/replication/FindReplicaDataSource.java
- backend/src/main/java/moheng/global/replication/RoutingDataSource.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
> #434 
<details>
</details>
- 데이터베이스 레플리케이션 환경을 구축했습니다.
- 1대의 Source 서버와 2대의 Replica 서버로 구분하여 라우팅 환경을 구축했습니다.
> [feat] 데이터베이스 레플리케이션 라우팅 환경 구축 

- backend/src/main/java/moheng/auth/application/AuthService.java
- backend/src/main/java/moheng/auth/presentation/authentication/AuthenticationArgumentResolver.java
- backend/src/main/java/moheng/auth/presentation/initauthentication/InitAuthenticationArgumentResolver.java
- backend/src/main/java/moheng/member/application/MemberService.java
- backend/src/test/java/moheng/auth/application/AuthServiceTest.java
> #437 
<details>
</details>
- 멤버 ID 추출 코드를 서비스 레이어로 전환 + Argument Resolver 가독성 개선
> [refactor] 토큰 인증/인가 도메인을 리팩토링 

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
> #441 
<details>
</details>
- 각 DBCP 의 HIkariCP 튜닝 값 적용
> [feat] 데이터베이스 다중화 환경에서 각 DB 에 HikariCP 최적 설정 값 적용 

- backend/src/main/java/moheng/global/cache/CacheConfig.java
- backend/src/main/java/moheng/global/cache/ExternalConcurrentMapSimilarTripCache.java
- backend/src/main/java/moheng/global/mdcfilter/AsyncConfig.java
> #436 
<details>
</details>
- 톰캣 서버 설정 튜닝에 따른 비동기 처리 쓰레드 풀 크기 재조정
> [feat] MDC 가 내부적으로 사용하는 쓰레드 로컬의 비동기 작업 풀 크기 설정 

- backend/src/main/java/moheng/global/aopquery/QueryCounterAop.java
- backend/src/main/resources/logback-spring.xml
> #451 
<details>
</details>
- MDC 형식 변경
> [refactor] MDC 기반 Logback, REQUEST_ID 포맷 변경 

- backend/src/main/java/moheng/recommendtrip/domain/tripfilterstrategy/TripLiveInformationFilterStrategy.java
> #448 
<details>
</details>
- 생활정보 여행지 필터링 전략 메소드 분리를 통한 가독성 개선
> refactor: 생활정보 여행지 필터링 전략 메소드 가독성 개선

- .github/workflows/docker-build.yml
> #458 
<details>
</details>
깃헙액션을 사용해서 컨테이너 이미지를 빌드하고
조직의 컨테이너 레지스트리 ghcr.io 업로드합니다.
> [feat] 깃헙 액션 & 패키지 업로드

- LICENSE
> #87
<details>
</details>
- MIT LICENSE 추가
> #463 docs: 라이센스 추가
