kakaotech-25/moheng

- backend/src/main/java/moheng/auth/dto/AccessTokenResponse.java
- backend/src/main/java/moheng/auth/presentation/AuthController.java
#46 
- 기존에 Request/Response Body 를 통해 송수신하던 RefreshToken 을 Header 내의 Cookie 에 감싸서 송수신하도록 구현했습니다.
> [feat] RefreshToken 전송시 Header 내의 Cookie 에 감싸도록 구현

- .github/events/pr.json
- .github/scripts/pr-deadline/caculate_deadline.sh
- .github/scripts/pr-deadline/extract_deadline.sh
- .github/scripts/pr-deadline/send_discord_notification.sh
- .github/workflows/pr-deadline-notifier.yml
> #62 
<details>
</details>
- 마감라벨의 D-DAY을 현재 시간에 더하여 마감기한을 디스코드 채널에 전송하는 기능
- D-0의 경우 당일의 자정시간을 기준으로 설정
> [feat] 풀리퀘스트의 라벨 마감기한을 DISCORD 웹훅으로 전송하는 기능

- .github/workflows/pr-deadline-notifier.yml
#74 
<details>
</details>
- discord 알림을 보내는 조건을 라벨 추출이 성공했을 때 동작하도록 변경
> [fix] 빈 라벨일 때 알림을 보내지 않도록 설정

- .github/scripts/pr-deadline/extract_deadline.sh
- .github/workflows/pr-deadline-notifier.yml
#74 
<details>
</details>
- D-day라벨이 아닌경우 exit 1로 종료하던 코드를 제거했습니다.
- action의 모든 job들이 if문으로 이전 파이프라인의 결과를 참조한 뒤 실행하도록 변경했습니다.
> [fix] D-day라벨이 아니어도 실패하지 않도록 수정

- backend/src/main/java/moheng/auth/application/AuthService.java
- backend/src/main/java/moheng/auth/presentation/authentication/AuthenticationBearerExtractor.java
- backend/src/main/java/moheng/keyword/domain/Keyword.java
- backend/src/main/java/moheng/member/presentation/MemberController.java
- backend/src/main/java/moheng/recommendtrip/domain/RecommendTrip.java
- backend/src/main/java/moheng/recommendtrip/domain/RecommendTripRepository.java
- backend/src/main/java/moheng/trip/application/TripService.java
- backend/src/main/java/moheng/trip/domain/recommendstrategy/AppendRecommendTripStrategy.java
- backend/src/main/java/moheng/trip/domain/recommendstrategy/RecommendTripStrategy.java
- backend/src/main/java/moheng/trip/domain/recommendstrategy/ReplaceRecommendTripStrategy.java
- backend/src/main/java/moheng/trip/domain/recommendstrategy/SaveRecommendTripStrategyProvider.java
- backend/src/main/java/moheng/trip/exception/NoExistRecommendTripStrategyException.java
- backend/src/test/java/moheng/acceptance/config/AcceptanceTestConfig.java
- backend/src/test/java/moheng/auth/presentation/AuthenticationBearerExtractorTest.java
- backend/src/test/java/moheng/config/DatabaseCleaner.java
- backend/src/test/java/moheng/config/slice/ControllerTestConfig.java
- backend/src/test/java/moheng/config/slice/RepositoryTestConfig.java
- backend/src/test/java/moheng/config/slice/ServiceTestConfig.java
- backend/src/test/java/moheng/keyword/domain/KeywordRepositoryTest.java
- backend/src/test/java/moheng/keyword/domain/TripKeywordRepositoryTest.java
- backend/src/test/java/moheng/liveinformation/domain/MemberLiveInformationRepositoryTest.java
- backend/src/test/java/moheng/member/domain/MemberRepositoryTest.java
- backend/src/test/java/moheng/member/presentation/MemberControllerTest.java
- backend/src/test/java/moheng/recommendtrip/domain/RecommendTripRepositoryTest.java
- backend/src/test/java/moheng/trip/application/AppendRecommendTripStrategyTest.java
- backend/src/test/java/moheng/trip/application/ReplaceRecommendTripStrategyTest.java
- backend/src/test/java/moheng/trip/domain/MemberTripRepositoryTest.java
- backend/src/test/resources/application.yml
#129 
<details>
</details>
- 현재 DirtiesContext 로 테스트 환경 격리 환경을 구축하고 있는데, 이는 ApplicationContext 를 캐싱하지 못한다는 단점으로 인해 빌드 속도가 매우 오래걸립니다. DirtiesContext 를  제거하고, 빌드 속도를 최적화했습니다. 
1.  `DirtiesContext` 제거
2. `DataBaseCleaner` 생성 : TRUNCATE 로 테이블 안의 모든 데이터를 초기화(삭제)
3. `슬라이스 테스트(Slice Test)` 기법으로 개선
3-1. 프레젠테이션 계층 테스트 최적화 : @MockBean 통합, https://github.com/SpringBootTest 를 @WebMvcTest 로 마이그레이션
3-2.  레포지토리 계층 테스트 최적화 : @DataJpaTest 로 마이그레이션
기존에 로컬 테스트 환경 기준 약 56초 가량 걸리던 테스트 빌드를, 리팩토링 결과 현재 약 3초로 크게 개선했습니다.
> [refactor] 테스트 격리 환경을 ApplicationContext 를 캐싱하고, 계층별 슬라이스 테스트를 적용하여 빌드 속도 최적화 

- frontend/src/components/Header/Header.css
- frontend/src/components/Header/Header.jsx
> #140
<details>
</details>
- 로그인 여부에 따라 헤더를 세가지의 구성으로 나누어서 렌더링해야 하는 부분이 있어서 해당 부분을 구현하였습니다.
- 아직 로그인 로직이 구현되지 않아 우선 세가지의 상황을 주석처리 해가며 확인하였습니다.
우선 변수는 다음과 같이 담았습니다.
useEffect를 통해 컴포넌트 마운트 시 내용을 판단하여 내부 구조를 변경하도록 하였습니다.
- '로그인' 버튼을 누르면 /login 페이지로 연동됩니다.
- /signup/profile , /signup/livinginfo, /signup/interestedplace 에서는 아무것도 보이지 않도록 하였습니다.
드롭다운 메뉴로 마이페이지, 플래너, 로그아웃이 보여지며 마우스 hover 시 배경이 어두워지도록 하였습니다.
> [feat] 로그인 여부에 따라 세가지 상황으로 헤더 구성 변경

- frontend/src/components/TravelCard/TravelCard.css
- frontend/src/components/TravelCarousel/TravelCarousel.css
- frontend/src/components/TravelCarousel/TravelCarousel.jsx
- frontend/src/pages/Home/Home.css
- frontend/src/pages/Home/Home.jsx
> #145
<details>
</details>
- 로그인 후 볼 수 있는 메인페이지를 구현하였습니다.
- 한 번에 5장의 여행지 카드를 볼 수 있으며 캐러셀 구조로 되어 있어 화살표를 누르면 옆으로 한칸씩 이동합니다.
- 위쪽은 AI를 통한 추천 여행지, 아래쪽은 키워드를 통한 필터링기능이 추가되어 있습니다.
- 키워드는 중복 선택이 가능하며 현재는 우선 더미 데이터에서 키워드를 추출해 테스트해보았습니다. 
자연 키워드를 선택하여 필터링된 결과를 보여줌
> [feat] 로그인 후 메인 페이지 UI 구현

- frontend/sonar-project.properties
> #196 
<details>
</details>
- 프론트엔드 sonar-project.properites에 JavaScript 및 JSX 파일에 대한 커버리지 측정을 비활성화하는 코드를 추가하였습니다.
> [fix] 프론트엔드 테스트 코드 커버리지 측정 비활성화

- nginx/tools/develop.conf
- nginx/tools/production.conf
> #198 
<details>
</details>
- docs 디렉토리로 요청이 오면 api/로 시작하지 않아 제대로 문서가 보이지 않는 현상을 해결했습니다.
> [fix] nginx 요청 docs 백엔드 컨테이너로 라우팅

- frontend/src/pages/TravelDetails/TravelDetails.css
- frontend/src/pages/TravelDetails/TravelDetails.jsx
> #195 
<details>
</details>
- 여행지 세부 페이지에서 [플래너에 담기] 버튼 누르면 일정에 여행지를 담을 수 있도록 모달 띄우기
- 일정 추가 버튼을 누르면 일정 추가하기 모달을 띄워주고 일정명, 일정기간을 입력하고 저장 누르면 리스트에 추가
[플래너에 담기] 버튼 누르면 모달 띄워줌
여러 일정에 담을 수 있도록 중복체크가 가능하도록 하였습니다.
새 일정 추가 모달에서 정보를 입력하고 저장을 누르면
일정리스트에 잘 들어가는 것을 확인할 수 있음
> [feat] 여행지세부페이지의 플래너에 담기 버튼을 눌렀을 때 일정리스트 모달 UI 구현

- frontend/src/pages/Login/Callback.jsx
- frontend/src/pages/Login/axiosInstance.jsx
> #253
<details>
</details>
- 엑세스 토큰 만료 시 리프레시 토큰을 확인하여 재발급받도록 하였습니다.
> [feat] 엑세스 토큰 만료시 리프레시 토큰을 통해 갱신하도록 하기 

- frontend/src/components/TravelCard/TravelCard.jsx
- frontend/src/components/TravelCarousel/TravelCarousel.jsx
- frontend/src/pages/InterestedPlace/InterestedPlace.jsx
> #231
<details>
</details>
- 최초입력3 페이지에서 관심여행지를 클릭하고 데이터를 전달하는 과정의 연동작업을 진행했습니다.
- 여행지캐러셀에서 태그 두개 주소는 구까지만 표시되도록 구현해둔 부분을 여행지카드에서 처리하도록 하였습니다. 태그가 하나인 곳은 하나만 나오도록 되어있습니다.
- GET 요청을 통해 여행지 데이터를 불러와서 여행지 카드 형태로 보여줍니다.
- 여행지는 5개 이상 10개 이하로 선택하도록 했고, 이 부분은 이미 프론트에서 구현이 된 부분이 있어서 프론트에서 확인하도록 했습니다.
- 완료버튼을 통해 POST 요청을 보내고 요청이 성공하면 메인페이지로 넘어가도록 했습니다.
- 완료버튼을 통해 최초가입과정이 모두 성공적으로 완료되면 정식회원이 되어서 최초입력에서는 403 오류가 나오는 것을 확인했습니다.
> [feat] 최초입력3-관심여행지 입력 페이지 연동 작업

- backend/src/main/java/moheng/global/mdcfilter/AsyncConfig.java
- backend/src/main/java/moheng/global/mdcfilter/MdcFilter.java
- backend/src/main/java/moheng/global/mdcfilter/MdcTaskDecorator.java
- backend/src/main/resources/logback-spring.xml
> #163 
<details>
</details>
- ThreadLocal 에 고유 ID 메타정보를 추가
-  로깅 관련 의존성 추가
멀티 쓰레드 환경에서 요청별 식별을 위해, 각 요청별로 고유 ID 로그를 생성했습니다. 예시는 다음과 같습니다. 
```
[REQUEST_ID] : fe06614d-7225-45a1-a91a-6513301ff176
[REQUEST_METHOD] : GET
[REQUEST_URI] : NO REQUEST URI
[REQUEST_TIME] : 2024-09-06 13:45:53.022
[REQUEST_IP] : localhost:8080
```
> [feat] Slf4j MDC 로 멀티쓰레드 환경에서 요청별 식별 고유 ID 로그 생성 

- backend/src/main/java/moheng/member/domain/Member.java
- backend/src/main/resources/static/docs/index.html
- backend/src/test/java/moheng/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/moheng/acceptance/PlannerAcceptenceTest.java
- backend/src/test/java/moheng/auth/domain/JwtTokenManagerTest.java
- backend/src/test/java/moheng/keyword/application/KeywordServiceTest.java
- backend/src/test/java/moheng/liveinformation/application/MemberLiveInformationServiceTest.java
- backend/src/test/java/moheng/liveinformation/domain/MemberLiveInformationRepositoryTest.java
- backend/src/test/java/moheng/member/application/MemberServiceTest.java
- backend/src/test/java/moheng/trip/application/TripServiceTest.java
> #293 
<details>
</details>
- 단일 API 를 호출했을떄는 문제 없이 동작하나, 간혹 여러 API 를 혼합하여 호출했을 시 비즈니스 로직을 만족하지 못하는 경우가 발생합니다. 이를 위한 인수 테스트를 진행하여, 더 믿음직한 프로뎍선 코드로 개선했습니다.
> [test] 유저 시나리오를 문서화화고, 여러 API 를 호출하는 E2E 인수 테스트 진행 

- backend/src/main/java/moheng/applicationrunner/dev/KeywordDevApplicationRunner.java
- backend/src/main/java/moheng/applicationrunner/dev/LiveInformationDevApplicationRunner.java
- backend/src/main/java/moheng/applicationrunner/dev/MemberLiveInformationDevApplicationRunner.java
- backend/src/main/java/moheng/applicationrunner/dev/TripDevApplicationRunner.java
- backend/src/main/java/moheng/keyword/application/KeywordService.java
- backend/src/main/java/moheng/keyword/domain/repository/TripKeywordRepository.java
- backend/src/main/java/moheng/keyword/domain/statistics/TripsByVisitedCountFinder.java
- backend/src/test/java/moheng/keyword/application/KeywordServiceTest.java
> #221 
<details>
</details>
- 이전에 N+1 과 같은 비정상적으로 쿼리가 많이 나가는 현상을 발견하고 해겷하기 위해 개발해놓은 쿼리 카운터를 활용했습니다.
-  키워드, 생활정보, 멤버 도메인에 비정상적으로 쿼리가 많이 나가는 로직들을 모두 `EntityGraph` 를 통해 N+1 문제를 해결했습니다.
> [refactor] 키워드, 생활정보, 멤버 도메인에 발생하는 N+1 문제 해결 및 쿼리 성능개선 

- compose.dev.yaml
- compose.frontend.yaml
- frontend/src/components/LivingBtn/LivingBtn.jsx
- frontend/src/components/UserForm/UserForm.jsx
- frontend/src/pages/LivingInfo/LivingInfo.jsx
- frontend/src/pages/Mypage/Mypage.jsx
- frontend/src/pages/Profile/Profile.jsx
- frontend/vite.config.js
> #236
<details>
</details>
- 마이페이지 연동작업을 진행했습니다.
- 프로필탭에서 중복검사 버튼을 누르면 403 에러가 뜨는 문제가 있어 확인해보니 최초입력1 페이지의 api를 사용하고 있던 문제를 발견했습니다. 이미 프로필탭에서 저장 버튼을 통해 닉네임의 중복여부를 확인하는 api가 있어 중복검사 버튼을 제거하였습니다.
- 생활탭에서 고령인 버튼을 누르면 저장이 되지 않는 문제가 있었습니다. 확인해보니 고령인이 아니라 고령자로 get이 되고 있어서 생기는 문제인 것을 파악하였고 고령자로 이름을 변경하였습니다.
- 프로필탭에서 카카오톡프로필의 사진과 최초회원가입시 입력한 닉네임, 생년월일, 성별 정보가 잘 불러와지는 것을 확인했고, 수정 후 저장버튼을 통해 업데이트되는 부분도 잘 작동하는 것을 확인했습니다.
- 생활탭에서도 true 값인 생활정보의 버튼이 클릭상태로 보여지는 것을 확인했고, 다른 버튼을 누르고 저장 시 해당 정보로 업데이트되는 것을 확인했습니다.
> [feat] 마이페이지 연동작업

- backend/src/docs/asciidoc/member.adoc
- backend/src/main/java/moheng/member/application/MemberService.java
- backend/src/main/java/moheng/member/dto/response/FindMemberAuthorityAndProfileResponse.java
- backend/src/main/java/moheng/member/presentation/MemberController.java
- backend/src/main/java/moheng/trip/infrastructure/ExternalAiRecommendModelClient.java
- backend/src/main/java/moheng/trip/infrastructure/ExternalAiSimilarTripModelClient.java
- backend/src/main/resources/application.yml
- backend/src/test/java/moheng/acceptance/MemberAcceptanceTest.java
- backend/src/test/java/moheng/acceptance/fixture/MemberAcceptanceFixture.java
- backend/src/test/java/moheng/member/application/MemberServiceTest.java
- backend/src/test/java/moheng/member/presentation/MemberControllerTest.java
> #319 
<details>
</details>
- 비회원, 최초 회원가입 유저, 정규 회원을 구분지어서 UI 상에 별도 이미지 및 상태값을 표시해야합니다. 이를 위한 기능을 구현했습니다.
> [test] 회원 상태 체크 및 헤더 상태 제공 API 테스트 코드 보강 

- backend/Dockerfile.dev
- backend/Dockerfile.prod
- compose.dev.yaml
> #325 
- 빌드 캐시가 남아서 업데이트가 되지않는 문제를 발견하여 backend gradlew clean build 로 변경하였습니다.
> [hotfix] gradlew clean build 명령어로 변경

- frontend/src/components/Header/Header.jsx
- frontend/src/pages/Login/axiosInstance.jsx
> #242
<details>
</details>
- 로그인 여부에 따라 헤더 구조가 변경되도록 하였습니다.
- 하지만 수정해야 할 부분이 몇 군데 있어 구현이 필요합니다. 현재 메인페이지연동작업이 가장 중요해서 해당 부분을 먼저 진행하도록 하겠습니다.
[수정해야 할 부분]
- 프로필이미지 동그랗게하고 드롭다운 맨 위에 보이도록 하기
- 새로고침해야 헤더가 바뀌는데 렌더링될 때 헤더가 바로 바뀌도록 해야 합니다.
> [feat] 로그인여부에 따른 헤더 구조 변경

- backend/src/main/java/moheng/keyword/application/KeywordService.java
- backend/src/main/resources/json/trip2.json
> #339 
<details>
</details>
- 키워드 필터링 맞춤 추천 여행지 조회시 빈 배열일 때 여행지가 조회되지 않는 현상 해결
> [fix] 키워드 필터링 맞춤 추천 여행지 조회시 빈 배열일 때 여행지가 조회되지 않는 현상 해결 

- backend/build.gradle
- backend/src/main/resources/static/docs/index.html
> #376 
<details>
</details>
- asciidoctor 테스크의 의존성을 build 테스크에 의존하도록 설정하여, API 명세가 정상 최신화되도록 설정합니다.
> [fix] asciidoctor 테스크의 의존성을 build 테스크에 의존하도록 설정

- compose.local.yaml
- compose.prod.yaml
- nginx/Dockerfile.local
- nginx/tools/develop.conf
> #364 
<details>
</details>
- 도커 네트워크의 경우 이름을 지어주지 않으면 디렉토리를 접두사로 붙여 사용하게 됩니다. 따라서 각기 다른 디렉토리에 있는 다른 두개의 도커파일을 동일한 네트워크에서 동작하게 하려면 이름을 명시적으로 지정해주어야합니다.
- nginx의 설정파일을 볼륨 마운트하는것으로 변경하였습니다. 
- nginx의 잘못된 포트번호 (5173 => 3000)로 수정했습니다.
>  #364 fix: 도커네트워크의 이름을 명시적으로 지정해주었습니다.

- backend/src/main/java/moheng/recommendtrip/domain/tripfilterstrategy/TripLiveInformationFilterStrategy.java
- backend/src/main/java/moheng/trip/application/TripService.java
- backend/src/main/java/moheng/trip/domain/repository/TripRepository.java
- backend/src/test/java/moheng/trip/application/TripServiceTest.java
> #294 
<details>
</details>
- 상세 여행지 조회시 방문수 카운팅 로직에서 발생하는 동시성 이슈를 비관적 락으로 해결했습니다.
> [feat] 상세 여행지 조회에서 발생하는 동시성 이슈를 비관적 락으로 해결 

- backend/src/main/java/moheng/global/error/ControllerAdvice.java
- backend/src/main/java/moheng/trip/application/TripService.java
- backend/src/main/java/moheng/trip/exception/NotAbleToAccessTripByPessimisticLock.java
> #294 
<details>
</details>
- 여행지 조회시 접속자 수가 많아 발생하는 동시성 이슈에 대한 상세 예외처리를 진행했습니다.
-  상태코드는 409 `Conflict` 로 처리했으며, 비관적 락에 대한 예외처리 클래스를 RuntimeException 으로 캐치합니다.
> [feat] 여행지 조회시 접속자 수가 많아 발생하는 동시성 이슈에 대한 상세 예외처리

- backend/src/main/java/moheng/global/cache/CacheConfig.java
- backend/src/main/java/moheng/global/cache/ExternalSimilarTripCache.java
- backend/src/main/java/moheng/recommendtrip/domain/tripfilterstrategy/TripLiveInformationFilterStrategy.java
- backend/src/main/java/moheng/trip/infrastructure/ExternalAiRecommendModelClient.java
- backend/src/main/java/moheng/trip/infrastructure/ExternalAiSimilarTripModelClient.java
> #425 
<details>
</details>
여행지 상세 페이지에서 비슷한 여행지를 조회하는데 성능이 꽤 좋지 않았습니다. 로컬에서 테스트한 결과 보통의 경우 약 `450ms` 정도의 결과가 도출되며, 간혹 최악의 경우엔 `600ms` 까지 소요되는 듯 합니다. 로컬이 아닌 개발 서버에서 테스트할 경우 더 오랜 시간이 걸리는 듯 합니다. 저희 모행 서비스를 이용하는데 여행지 조회시 걸리는 시간이 꽤 오래걸려서, 개발자인 저희 조차 답답함과 불편함이 느껴졌습니다. 외부 API 를 호출하는 방식 이기 떄문에, 데이터베이스 인덱스 적용도 불가능한 상태라, 성능을 어떻게 최적화할지 고민이 많았습니다.
이에 대한 성능을 최적화 하고자 했습니다. `로컬 캐시` 를 이용하여, 캐싱된 내용을 읽어오도록 성능을 최적화했습니다. 그 결과는 로컬 테스트 기준 약 `20ms` 정도의 성능으로 개선되었네요. 이후 개발 서버에서도 성능이 얼마나 나오는지 테스트 해보고자 합니다.
스프링에서 기본적으로 제공하는 캐시 구현체는 `ConcurrentMapCache` 입니다. 다만, TTL 이 존재하지 않아 외부 캐시 저장소인 `Redis` 나 `Encache` 를 구현할 수도 있었지만, 충분히 로컬 캐시를 커스터마이징하여 TTL 기능을 만들 수 있겠다고 생각이 들었어요.
실제로  `ConcurrentMapCache` 를 상속한 캐시 구현체를 직접 만들었습니다. TTL 기능을 지원하여 …
> [feat] 로컬 캐시를 사용한 외부 API 요청 최적화 

- backend/src/main/resources/application-dev.yml
> #440 
<details>
</details>
- JPA OSIV 를 비활성화하여 DB 레플리케이션 환경에서 라우팅이 정상 동작하지 않는 문제를 해결했습니다.
- OSIV를 비활성화하면 영속성 컨텍스트의 생존 범위는 트랜잭션 시작부터 종료까지로 좁혀집니다. 즉, 트랜잭션이 시작될 때 영속성 컨텍스트가 실행되고, 트랜잭션이 끝날 때 까지 유지됩니다. 즉, 영속성 컨텍스트가 여러번 생성되고, 커넥션도 여러번 획득하고, 따라서 DataSource 도 개별 트랜잭션마다 선택됩니다. 즉, DataSource 의 분기가 정상적으로 이루어집니다.
> [fix] Argument Resolver 를 사용시 DB 레플리케이션 환경에서 DataSource 라우팅이 안되는 문제 해결 
